import * as React from 'react';
import { mount } from 'enzyme';

import { deepAssign } from '../../test/utils/deep-assign';
import Markdown from '../Markdown';
import AutoExample from '../AutoExample';
import StoryPage from './index';
import { AutoTestkit } from '../AutoTestkit/auto-testkit';

export default class {
  component;

  defaultProps = {
    metadata: {
      props: {},
    },
    config: {},
    component: () => <div />,
    componentProps: {},
    exampleProps: {},
    examples: null,
  };

  when = {
    created: props =>
      (this.component = mount(
        <StoryPage {...deepAssign(this.defaultProps, props)} />,
      )),
  };

  get = {
    readme: () =>
      this.component.find('[dataHook="metadata-readme"]').prop('source'),

    import: () =>
      this.component
        .find('[dataHook="metadata-import"]')
        .find(Markdown)
        .prop('source'),

    codeBlock: () =>
      this.component.find('[dataHook="metadata-codeblock"]').find(Markdown),

    autoExample: () => this.component.find(AutoExample),

    api: {
      markdown: () => {
        return this.component.find('[data-hook="api-markdown"]');
      },
    },

    testkit: {
      markdown: () => {
        return this.component.find('[data-hook="testkit-markdown"]');
      },
      autoGenerated: () => this.component.find(AutoTestkit),
    },
  };
}
